//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;

public partial class RealStarIceCreamEntities2 : DbContext
{
    public RealStarIceCreamEntities2()
        : base("name=RealStarIceCreamEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<CategoryInfo> CategoryInfoes { get; set; }
    public DbSet<EnquiryInfo> EnquiryInfoes { get; set; }
    public DbSet<ImageSlider> ImageSliders { get; set; }
    public DbSet<loginInfo> loginInfoes { get; set; }
    public DbSet<ProductInfo> ProductInfoes { get; set; }

    public virtual int GetCustomersPageWise(Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
    {
        var pageIndexParameter = pageIndex.HasValue ?
            new ObjectParameter("PageIndex", pageIndex) :
            new ObjectParameter("PageIndex", typeof(int));

        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetCustomersPageWise", pageIndexParameter, pageSizeParameter, recordCount);
    }

    public virtual int GetProductsPageWise(Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
    {
        var pageIndexParameter = pageIndex.HasValue ?
            new ObjectParameter("PageIndex", pageIndex) :
            new ObjectParameter("PageIndex", typeof(int));

        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetProductsPageWise", pageIndexParameter, pageSizeParameter, recordCount);
    }

    public virtual int GetProductsPageWiseForSelectedCategory(Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount, Nullable<int> categoryId)
    {
        var pageIndexParameter = pageIndex.HasValue ?
            new ObjectParameter("PageIndex", pageIndex) :
            new ObjectParameter("PageIndex", typeof(int));

        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("PageSize", pageSize) :
            new ObjectParameter("PageSize", typeof(int));

        var categoryIdParameter = categoryId.HasValue ?
            new ObjectParameter("CategoryId", categoryId) :
            new ObjectParameter("CategoryId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetProductsPageWiseForSelectedCategory", pageIndexParameter, pageSizeParameter, recordCount, categoryIdParameter);
    }

    public virtual ObjectResult<Nullable<decimal>> prcAddProducts(string productTitle, string photoName, string extName, string photoType, Nullable<int> photoSize, Nullable<int> categoryId)
    {
        var productTitleParameter = productTitle != null ?
            new ObjectParameter("ProductTitle", productTitle) :
            new ObjectParameter("ProductTitle", typeof(string));

        var photoNameParameter = photoName != null ?
            new ObjectParameter("PhotoName", photoName) :
            new ObjectParameter("PhotoName", typeof(string));

        var extNameParameter = extName != null ?
            new ObjectParameter("ExtName", extName) :
            new ObjectParameter("ExtName", typeof(string));

        var photoTypeParameter = photoType != null ?
            new ObjectParameter("PhotoType", photoType) :
            new ObjectParameter("PhotoType", typeof(string));

        var photoSizeParameter = photoSize.HasValue ?
            new ObjectParameter("PhotoSize", photoSize) :
            new ObjectParameter("PhotoSize", typeof(int));

        var categoryIdParameter = categoryId.HasValue ?
            new ObjectParameter("CategoryId", categoryId) :
            new ObjectParameter("CategoryId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("prcAddProducts", productTitleParameter, photoNameParameter, extNameParameter, photoTypeParameter, photoSizeParameter, categoryIdParameter);
    }

    public virtual ObjectResult<Nullable<decimal>> prcAddSliderPhoto(string photoName, string extName, string photoType, Nullable<int> photoSize)
    {
        var photoNameParameter = photoName != null ?
            new ObjectParameter("PhotoName", photoName) :
            new ObjectParameter("PhotoName", typeof(string));

        var extNameParameter = extName != null ?
            new ObjectParameter("ExtName", extName) :
            new ObjectParameter("ExtName", typeof(string));

        var photoTypeParameter = photoType != null ?
            new ObjectParameter("PhotoType", photoType) :
            new ObjectParameter("PhotoType", typeof(string));

        var photoSizeParameter = photoSize.HasValue ?
            new ObjectParameter("PhotoSize", photoSize) :
            new ObjectParameter("PhotoSize", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("prcAddSliderPhoto", photoNameParameter, extNameParameter, photoTypeParameter, photoSizeParameter);
    }

    public virtual int prcInsertEnquiryInfo(string name, string email, Nullable<long> mobile, string subject, string message, Nullable<System.DateTime> enquiryDate)
    {
        var nameParameter = name != null ?
            new ObjectParameter("Name", name) :
            new ObjectParameter("Name", typeof(string));

        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));

        var mobileParameter = mobile.HasValue ?
            new ObjectParameter("Mobile", mobile) :
            new ObjectParameter("Mobile", typeof(long));

        var subjectParameter = subject != null ?
            new ObjectParameter("Subject", subject) :
            new ObjectParameter("Subject", typeof(string));

        var messageParameter = message != null ?
            new ObjectParameter("Message", message) :
            new ObjectParameter("Message", typeof(string));

        var enquiryDateParameter = enquiryDate.HasValue ?
            new ObjectParameter("EnquiryDate", enquiryDate) :
            new ObjectParameter("EnquiryDate", typeof(System.DateTime));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcInsertEnquiryInfo", nameParameter, emailParameter, mobileParameter, subjectParameter, messageParameter, enquiryDateParameter);
    }

    public virtual ObjectResult<prcSelectAllProducts_Result> prcSelectAllProducts()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcSelectAllProducts_Result>("prcSelectAllProducts");
    }

    public virtual ObjectResult<prcSelectCategorywiseProducts_Result> prcSelectCategorywiseProducts(Nullable<int> categoryId)
    {
        var categoryIdParameter = categoryId.HasValue ?
            new ObjectParameter("CategoryId", categoryId) :
            new ObjectParameter("CategoryId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcSelectCategorywiseProducts_Result>("prcSelectCategorywiseProducts", categoryIdParameter);
    }

    public virtual int PrcUpdatePswd(string oldpswd, string newPswd, string userid)
    {
        var oldpswdParameter = oldpswd != null ?
            new ObjectParameter("Oldpswd", oldpswd) :
            new ObjectParameter("Oldpswd", typeof(string));

        var newPswdParameter = newPswd != null ?
            new ObjectParameter("NewPswd", newPswd) :
            new ObjectParameter("NewPswd", typeof(string));

        var useridParameter = userid != null ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PrcUpdatePswd", oldpswdParameter, newPswdParameter, useridParameter);
    }

    public virtual ObjectResult<PrcViewAllEnquiries_Result> PrcViewAllEnquiries()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrcViewAllEnquiries_Result>("PrcViewAllEnquiries");
    }

    public virtual ObjectResult<prcViewCategoriesInDescOrder_Result> prcViewCategoriesInDescOrder()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prcViewCategoriesInDescOrder_Result>("prcViewCategoriesInDescOrder");
    }
}
